package com.flf.entity;

import java.math.BigDecimal;
import java.text.DecimalFormat;
import java.util.Date;
import java.util.List;


/**
 * SysUser generated by MyEclipse - Hibernate Tools
 */

public class TbBatch  implements java.io.Serializable {


    // Fields    

     /**
	 * 
	 */
	 private static final long serialVersionUID = -6261343754663212034L;
	 private Integer batchId;
     private String batchNum;  //批次号
     private String uploadTime;  //上传时间
     private String uploadMan;  //上传人
     private Page page;
     private String sql;
     //以下为easyUI 显示隐藏列 tb_user_menu
     private Integer uId;//用户id
     private Integer type;//0：查看详情页面 1：样本查询页面
     private Long bId;//批次id
     private String menuName;//easyui 隐藏列名

	public static long getSerialVersionUID() {
		return serialVersionUID;
	}

	public Integer getBatchId() {
		return batchId;
	}

	public void setBatchId(Integer batchId) {
		this.batchId = batchId;
	}

	public String getBatchNum() {
		return batchNum;
	}

	public void setBatchNum(String batchNum) {
		this.batchNum = batchNum;
	}

	public String getUploadTime() {
		return uploadTime;
	}

	public void setUploadTime(String uploadTime) {
		this.uploadTime = uploadTime;
	}

	public String getUploadMan() {
		return uploadMan;
	}

	public void setUploadMan(String uploadMan) {
		this.uploadMan = uploadMan;
	}

	public Page getPage() {
		return page;
	}

	public void setPage(Page page) {
		this.page = page;
	}

	public String getSql() {
		return sql;
	}

	public void setSql(String sql) {
		this.sql = sql;
	}

	public Integer getuId() {
		return uId;
	}

	public void setuId(Integer uId) {
		this.uId = uId;
	}

	public Integer getType() {
		return type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public Long getbId() {
		return bId;
	}

	public void setbId(Long bId) {
		this.bId = bId;
	}

	public String getMenuName() {
		return menuName;
	}

	public void setMenuName(String menuName) {
		this.menuName = menuName;
	}
}