package com.flf.entity;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import com.sun.xml.internal.ws.developer.StreamingAttachment;

/**
 * SysUser generated by MyEclipse - Hibernate Tools
 */

public class TbSample implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = -6261343754663212034L;
	private Long tbSampleId;
	private Integer batchId; // 批次号外键
	private String foodSubclass; //食品次亚类
	private String packing;// 包装分类
	private String area;// 区域类型
	private String location;// 抽样地点
	private String link;// 抽样环节
	private String province;// 抽样省
	private String sampleState;// 样品状态
	private String sampeType;// 样品类型
	private String productionProvince;// 生产省
	private String zone;// 经济地带
	private String sampleQuarter;// 抽样季度
	private String productionQuarter;// 生产季度
	private String guaranteeQualityRate;// 保质率
	private String salesVolume;// 年销售额
	private String sorbicAcid;// 山梨酸
	private String nitrite;// 亚硝酸盐
	private String lead;// 铅
	private String chromium;// 铬
	private String cadmium;// 镉
	private String risk;// 风险值
	private String sql;
	private Page page;

	public Page getPage() {
		return page;
	}

	public void setPage(Page page) {
		this.page = page;
	}

	public static long getSerialVersionUID() {
		return serialVersionUID;
	}

	public Long getTbSampleId() {
		return tbSampleId;
	}

	public void setTbSampleId(Long tbSampleId) {
		this.tbSampleId = tbSampleId;
	}

	public Integer getBatchId() {
		return batchId;
	}

	public void setBatchId(Integer batchId) {
		this.batchId = batchId;
	}

	public String getFoodSubclass() {
		return foodSubclass;
	}

	public void setFoodSubclass(String foodSubclass) {
		this.foodSubclass = foodSubclass;
	}

	public String getArea() {
		return area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	public String getLocation() {
		return location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public String getLink() {
		return link;
	}

	public void setLink(String link) {
		this.link = link;
	}

	public String getProvince() {
		return province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	public String getSampleState() {
		return sampleState;
	}

	public void setSampleState(String sampleState) {
		this.sampleState = sampleState;
	}

	public String getSampeType() {
		return sampeType;
	}

	public void setSampeType(String sampeType) {
		this.sampeType = sampeType;
	}

	public String getProductionProvince() {
		return productionProvince;
	}

	public void setProductionProvince(String productionProvince) {
		this.productionProvince = productionProvince;
	}

	public String getZone() {
		return zone;
	}

	public void setZone(String zone) {
		this.zone = zone;
	}

	public String getSampleQuarter() {
		return sampleQuarter;
	}

	public void setSampleQuarter(String sampleQuarter) {
		this.sampleQuarter = sampleQuarter;
	}

	public String getProductionQuarter() {
		return productionQuarter;
	}

	public void setProductionQuarter(String productionQuarter) {
		this.productionQuarter = productionQuarter;
	}

	public String getGuaranteeQualityRate() {
		return guaranteeQualityRate;
	}

	public void setGuaranteeQualityRate(String guaranteeQualityRate) {
		this.guaranteeQualityRate = guaranteeQualityRate;
	}

	public String getSalesVolume() {
		return salesVolume;
	}

	public void setSalesVolume(String salesVolume) {
		this.salesVolume = salesVolume;
	}

	public String getSorbicAcid() {
		return sorbicAcid;
	}

	public void setSorbicAcid(String sorbicAcid) {
		this.sorbicAcid = sorbicAcid;
	}

	public String getNitrite() {
		return nitrite;
	}

	public void setNitrite(String nitrite) {
		this.nitrite = nitrite;
	}

	public String getLead() {
		return lead;
	}

	public void setLead(String lead) {
		this.lead = lead;
	}

	public String getChromium() {
		return chromium;
	}

	public void setChromium(String chromium) {
		this.chromium = chromium;
	}

	public String getCadmium() {
		return cadmium;
	}

	public void setCadmium(String cadmium) {
		this.cadmium = cadmium;
	}

	public String getRisk() {
		return risk;
	}

	public void setRisk(String risk) {
		this.risk = risk;
	}

	public String getPacking() {
		return packing;
	}

	public void setPacking(String packing) {
		this.packing = packing;
	}

	public String getSql() {
		return sql;
	}

	public void setSql(String sql) {
		this.sql = sql;
	}
}